language: csharp
rust:
- stable
branches:
  only:
  - master

matrix:
  include:
    - os: osx
      env: OSTAG=Darwin
  include:
    - os: linux
      env: OSTAG=Linux

install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source $HOME/.cargo/env
script:
  - cargo test --release
  - dotnet build -c Release dotnet//RuAnnoy-Batteries-${OSTAG}-x64/RuAnnoy-Batteries-${OSTAG}-x64.csproj

mono: none
dotnet: "2.1.300"
