language: csharp
sudo: true
mono: none
dist: xenial
dotnet: 2.2.203
os:
  - osx
  - linux
env:
  matrix:
    - OSTAG=Darwin
    - OSTAG=Linux
  global:
    secure: Z7SHzBfOxVUNegEAmCrSXd6RrAzlvFkKSb19wBuqQUDg9+Tnql/PvUGJk5ZUzB1mPL3AZraNDdY1OUqttkvZmfZ4qd7L2gte2skjF835OLvrATUB2jrGI3rAYG2f8c5X03Df+rcZpCf4MoXZMLNd00EDzeAFaK7mXBDaUA5aCdMlSvYCD0bAaQAtJxNP48SVZmY6KaP+htSczZIDi5XywTY471hZ/b8eFqhYlKjmMIQc4qZ+R3Bna4g16sQDndN3/gpa3Dk7E7uEwtoFhp/ujECX24OhzlXxKfpTSa3/VAb837Nv6jIJdEn719vduoS3/FvT6jcKd7UFOlYWGqrL8Z0autUCZ6iGkKDGHY46rY/7EXfr5gTh+veT/2Hw75dsa7zqxNsmZNhI6Ni1yXqsGvmwBzvxBPUgrNfKK/H9LUzeTJLHrQgwIhwH0EaYFMo3CbDViIT+6gL4GsjCK3pC/GaXl8u19oa5/1/QQrn1e0QiKF3fldh5xM2TGUiOx8KQAg7WvMBbx8O7S+VAS5spg9Tg4tD1h/jfGKPlTb10JFcXlZo4Ytn7XhdMEnorz+ONXiVKqm1csu0R4Qj118/7HDdo0lqxUDv1cYEpm5k8usULhx00j190aDTjwfdh1YQr3HyO4UGZeQIxfw2YxjAEDnn3oKxL1hTOku2hXzgOCfI=
branches:
  only:
    - master
install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source $HOME/.cargo/env
  - rustup default stable
  - rustup component add rustfmt
  - cargo -V
  - rustc -V
script:
  - cargo build --release
  - cargo test --release
  - cargo build --release --features cffi
  - cargo test --release --features cffi
  - cargo fmt --all -- --check
  - dotnet build ${TRAVIS_BUILD_DIR}/dotnet/RuAnnoy-Batteries-${OSTAG}-x64/RuAnnoy-Batteries-${OSTAG}-x64.csproj -c Release
  - mkdir ${TRAVIS_BUILD_DIR}/artifacts/
  - cp ${TRAVIS_BUILD_DIR}/dotnet/RuAnnoy-Batteries-${OSTAG}-x64/bin/Release/*.nupkg ${TRAVIS_BUILD_DIR}/artifacts/
#deploy:
#  skip_cleanup: true
#  provider: script
#  script: dotnet nuget push ${TRAVIS_BUILD_DIR}/artifacts/*.nupkg -k ${NUGET_API_KEY}
#  on:
#    branch: master
#    os: osx
matrix:
  exclude:
    - os: osx
      env: OSTAG=Linux
    - os: linux
      env: OSTAG=Darwin
