language: csharp
mono: none
dotnet: "2.1.300"
os:
  - osx
  - linux
env:
  - OSTAG=Darwin
  - OSTAG=Linux
branches:
  only:
  - master

install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source $HOME/.cargo/env
script:
  - cargo test --release
  - dotnet build -c Release dotnet//RuAnnoy-Batteries-${OSTAG}-x64/RuAnnoy-Batteries-${OSTAG}-x64.csproj

matrix:
  exclude:
    - os: osx
      env: OSTAG=Linux
  exclude:
    - os: linux
      env: OSTAG=Darwin
