language: csharp
rust:
- stable
install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source $HOME/.cargo/env
branches:
  only:
  - master
script:
  - cargo test --release
mono: none
dotnet: "2.1.300"
os:
 - osx
 - linux
matrix:
  fast_finish: true
  include:
  - os: osx
  script:
  - cargo test --release
  - dotnet build -c Release dotnet//RuAnnoy-Batteries-Darwin-x64/RuAnnoy-Batteries-Darwin-x64.csproj
  include:
  - os: linux
  script:
  - cargo test --release
  - dotnet build -c Release dotnet//RuAnnoy-Batteries-Linux-x64/RuAnnoy-Batteries-Linux-x64.csproj
