language: csharp
rust:
- stable
install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source $HOME/.cargo/env
script:
  - cargo test --release
branches:
  only:
  - master
os:
  - linux
mono: none
dotnet: "2.1.300"
matrix:
  fast_finish: true
  include:
  - os: osx
  script:
  - cargo test --release
  - dotnet build -c Release dotnet//RuAnnoy-Batteries-Darwin-x64/RuAnnoy-Batteries-Darwin-x64.csproj
  branches:
  only:
  - master
