language: rust
matrix:
  include:
    - os: linux
      rust: nightly
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.rustup/
    - $HOME/.cargo/
before_install:
  - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
install:
  - cargo -V
  - rustup component add llvm-tools-preview
  - export RUSTFLAGS="-Zinstrument-coverage"
script:
  - cargo build --all-features
  - LLVM_PROFILE_FILE="hanabi1224-%p-%m.profraw" cargo test --all-features
  - ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
  - bash <(curl -s https://codecov.io/bash) -f lcov.info
