language: csharp
mono: none
dotnet: "2.1.300"
os:
  - osx
  - linux
env:
  - OSTAG=Darwin
  - OSTAG=Linux
  #- NUGET_API_KEY:
  #  - secure: 
branches:
  only:
  - master

install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source $HOME/.cargo/env
script:
  - cargo build --release
  - cargo test --release
  - echo dotnet/RuAnnoy-Batteries-${OSTAG}-x64/RuAnnoy-Batteries-${OSTAG}-x64.csproj
  - dotnet build -c Release dotnet/RuAnnoy-Batteries-${OSTAG}-x64/RuAnnoy-Batteries-${OSTAG}-x64.csproj
deploy:
  provider: script
  script: bash dotnet/upload_nuget.sh
  on:
    branch: master
matrix:
  exclude:
    - os: osx
      env: OSTAG=Linux
    - os: linux
      env: OSTAG=Darwin
