image:
  - Ubuntu
  - Visual Studio 2019
environment:
  matrix:
    - RUST_TOOL_CHAIN: stable
test_script:
  - cargo test --release
  - cargo test --release --features cffi
branches:
  only:
    - master
pull_requests:
  do_not_increment_build_number: true
artifacts:
  - path: '**\*.nupkg'
    name: nupkg
  - path: '**\*.snupkg'
    name: snupkg
nuget:
  disable_publish_on_pr: true
deploy:
  provider: NuGet
  api_key:
    secure: oAHIyS9ywws1FkW2wadKEGo3WLcNo41ERWTJFxkmKz4nZrE3KH28eJjkrRSQmWbN
matrix:
  fast_finish: true
for:
  - matrix:
      only:
        - image: Ubuntu
    install:
      - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain ${RUST_TOOL_CHAIN}
      - source $HOME/.cargo/env
      - rustup component add rustfmt
    build_script:
      - cargo build --release --features cffi
      - cargo fmt --all -- --check
      - dotnet build -c Release dotnet/RuAnnoy-Batteries-Linux-x64/RuAnnoy-Batteries-Linux-x64.csproj
  - matrix:
      only:
        - image: Visual Studio 2019
    install:
      - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
      - scoop install rustup
      - refreshenv
      #- SET PATH=%USERPROFILE%\scoop\apps\rustup\current\.cargo\bin;%PATH%
      - rustup default %RUST_TOOL_CHAIN%
      - rustup component add rustfmt
      #- SET PATH=%USERPROFILE%\.cargo\bin;C:\MinGW\bin;%PATH%
      - rustc -V
      - cargo -V
    build_script:
      - cargo build --release --features cffi
      - cargo fmt --all -- --check
      - dotnet build -c Release dotnet/RuAnnoy/RuAnnoy.csproj
      - dotnet build -c Release dotnet/RuAnnoy-Batteries-Windows-x64/RuAnnoy-Batteries-Windows-x64.csproj
