image:
  - ubuntu
  - Visual Studio 2017
environment:
  matrix:
  - RUST_TOOL_CHAIN: stable
  #- RUST_TOOL_CHAIN: nightly
test_script:
  - cargo test --release
branches:
  only:
    - master
pull_requests:
  do_not_increment_build_number: true
artifacts:
  - path: '**\*.nupkg'
nuget:
  disable_publish_on_pr: true
deploy:
  provider: NuGet
  api_key:
    secure: nNWiXk+ZiOOh5sHV/C9Z9pqZ8GFpaQFqAR/P0/t09h81Ppx3xed6VsWd4w7FMn2R
matrix:
  fast_finish: true
for:
  -
    matrix:
      only:
        - image: Ubuntu
    install:
      - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain ${RUST_TOOL_CHAIN}
      - source $HOME/.cargo/env
      - rustup component add rustfmt-preview
    build_script:
      - cargo build --release
      - cargo fmt --all -- --check
      - dotnet build -c Release dotnet/RuAnnoy-Batteries-Linux-x64/RuAnnoy-Batteries-Linux-x64.csproj
  -
    matrix:
      only:
        - image: Visual Studio 2017
    install:
      - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
      - scoop install rustup@1.14.0
      - refreshenv
      #- SET PATH=%USERPROFILE%\scoop\apps\rustup\current\.cargo\bin;%PATH%
      - rustup default %RUST_TOOL_CHAIN%
      - rustup component add rustfmt-preview
      #- SET PATH=%USERPROFILE%\.cargo\bin;C:\MinGW\bin;%PATH%
      - rustc -V
      - cargo -V
    build_script:
      - cargo build --release
      - cargo fmt --all -- --check
      - dotnet build -c Release dotnet/RuAnnoy/RuAnnoy.csproj
      - dotnet build -c Release dotnet/RuAnnoy-Batteries-Windows-x64/RuAnnoy-Batteries-Windows-x64.csproj
