[package]
authors = ["hanabi1224"]
description = """
A rust implementation of annoy(https://github.com/spotify/annoy) (Index serving only). Providing C api as well
"""
edition = "2018"
exclude = ["dotnet", "java", "test_gen", ".idea", ".vscode", ".github", "*.yml", "*.iml", ".gitignore"]
license = "MIT"
name = "ru_annoy"
repository = "https://github.com/hanabi1224/RuAnnoy"
version = "0.1.4"

[features]
cffi = ["libc"]
simd = ["core_simd"]

[dependencies]
# ahash = "0"
cfg-if = "1"
# core_simd = { git = "https://github.com/rust-lang/stdsimd" }
core_simd = { git = "https://github.com/rust-lang/stdsimd", optional = true }
hashbrown = "0"
libc = {version = "0", optional = true}
memmap2 = "0"
# packed_simd_2 = "0"
lazy_static = "1"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
