[package]
edition = "2021"
name = "bencher"
version = "0.1.0"

[features]
simd = ["annoy-rs/simd"]

[dependencies]
annoy-rs = {path = "../../"}

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
overflow-checks = false
