[package]
authors = ["hanabi1224 <harlowmoo@gmail.com>"]
edition = "2018"
name = "bencher"
version = "0.1.0"

[features]
simd = ["ru_annoy/simd"] 

[dependencies]
ru_annoy = {path = "../../"}

[profile.release]
debug = true
