[package]
authors = ["hanabi1224 <harlowmoo@gmail.com>"]
edition = "2018"
name = "bencher"
version = "0.1.0"

[features]
simd = ["annoy-rs/simd"]

[dependencies]
annoy-rs = {path = "../../"}

[profile.release]
debug = true
