name: main

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: actions/checkout@v2
      - name: Cargo Build
        run: |
          cargo build --release
          cargo build --release --all-features
      - name: Cargo Test
        run: |
          cargo test --release
          cargo test --release --all-features
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: java Test
        run: |
          pushd java
          ./gradlew test
      - name: dotnet Test
        run: |
          dotnet test -c Release dotnet/RuAnnoy.Tests
      - name: dotnet Build - Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          dotnet build -c Release dotnet/RuAnnoy-Batteries-Linux-x64
      - name: dotnet Build - OSX
        if: matrix.os == 'macos-latest'
        run: |
          dotnet build -c Release dotnet/RuAnnoy-Batteries-Darwin-x64
      - name: dotnet Build - Windows
        if: matrix.os == 'windows-latest'
        run: |
          dotnet build -c Release dotnet/RuAnnoy-Batteries-Windows-x64
          dotnet build -c Release dotnet/RuAnnoy
      - uses: actions/upload-artifact@v2
        with:
          path: dotnet/**/*.nupkg
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        with:
          path: dotnet/**/*.snupkg
